### ISSUE TITLE
Get youngest block feature

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#139]
**IMPORTANT:**
There is a branch called `get-youngest-block`. Make a branch based off of this branch to work on. Please do **not** push to this branch directly.

**Desired Date of Completion:** 14-April-2019

**Workspace:**
- producer blockchain package

**Objective:**
When creating the newest block, the producer will require information about the latest block, starting all the way from the genesis block. Important information includes the version, timestamp, and height. I've created a new struct called `BlockHeader` in block which will contain the static-sized information of all Aurum Blocks, called the Header. It might be a good idea to eventually make the `Block` struct composed of a `BlockHeader` and `BlockBody`.

The `blockchain` package in the `get-youngest-block` branch has function stubs and unit tests. Please refrain from changing the unit tests. If it is absolutely necessary, please make a comment first, and then we can both discuss changing them.

**Resources:**
- golang sqlite3: [github.com/mattn/go-sqlite3](https://godoc.org/github.com/mattn/go-sqlite3)
- [sqlite3 Tutorial](https://www.thepolyglotdeveloper.com/2017/04/using-sqlite-database-golang-application/)
- [another sqlite3 Tutorial](https://astaxie.gitbooks.io/build-web-application-with-golang/en/05.3.html)

**Comment by HarryL5004** [comment]
In the unit test, should I include `defer` before `tearDown`? Because otherwise it will remove those files immediately after creating them.
![image](https://user-images.githubusercontent.com/42977312/56054405-564f0f00-5d1c-11e9-86e6-9505ffa2b508.png)

Also, in line 374 of `blockchain_test.go`, should I change `GetYoungestBlock` function to `GetYoungestBlockHeader` so that the unit test compares the header of the youngest block rather than comparing a block and a block header?
![image](https://user-images.githubusercontent.com/42977312/56054863-91057700-5d1d-11e9-9313-9d255f964c26.png)

**Comment by kstola2** [comment]
@HarryL5004 yes sorry I must've missed that.

**Comment by HarryL5004** [comment]
Completed
