### ISSUE TITLE
Client Wallet Functions

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#195]
Make a branch based on the getnonce branch. In the client package, there are three functions to write: GetNonce(), GetWalletAddress(), and GetBalance(). These functions will be used when users send Aurum to each other, among other uses.

GetNonce should return a uint64 from a wallet.
GetBalance should return a unint64 from a wallet.
GetWalletAddress should return a hashed byte slice from a wallet (Use the SHA256 hash of public key)

Please handle all error gracefully!

Please include issue number in all commits and comments.

**Comment by HarryL5004** [comment]
I noticed a problem with the test for `GetBalance(...)`:
`432: 	wallet, err := os.Open("aurum_wallet.json")`
`450:	_, err = wallet.Write(updatedWalletJSON)`
Since `os.Open(...)` opens the file with the flag `O_RDONLY`, `wallet.Write(...)` will return an error stating `Access is denied` and nothing will be written into the json file.

I also have a question for `GetBalance(...)`. Since there's already another function in `client` called `CheckBalance(...)` that retrieves and prints the balance from a wallet, wouldn't it be redundant to add `GetBalance(...)` that performs basically the same tasks (except printing the balance out)?

**Comment by bashbashbash** [comment]
Good catch and my bad - tests have been updated where json is being modified. You are correct that GetBalance essentially does the same thing that checkBalance does. My thought is that we would update checkbalance to call getbalance or eliminate entirely, but we'll discuss with Karol when the implementation is complete.

**Comment by kstola2** [comment]
@HarryL5004 @bashbashbash Yes `GetBalance` and `CheckBalance` are redundant. `GetBalance` is what we want, but I would like to be safe and just build the new function and once that's complete we will delete `CheckBalance`. Consider it a guide for now.

**Comment by HarryL5004** [comment]
`432: wallet, err := os.OpenFile("aurum_wallet.json", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)`
`437: bytes, _ := ioutil.ReadAll(wallet)`

Umm...now the test cannot read from the json file because of the flag `O_WRONLY`. I think you should use the flag `O_RDWR` (which stands for read and write) instead.

Also, I don't think it is a good idea to include the `append` flag and the `create` flag. `SetupWallet()` creates the json file so the create flag is redundant. The append flag will append whatever you wrote into the file, which means that you are not actually changing the balance of the client's wallet for the test, but appending a new wallet data struct into the json file.

**Comment by kstola2** [comment]
@zach please just do as we discussed and use the code in the setupwallet body to create variable fields in the test. this is becoming more frustrating than it needs to be

**Comment by bashbashbash** [comment]
@HarryL5004 take a quick look if the change I made resolved the problem (since it was only a one line change). If no good, I'll implement the solution Karol and I discussed

**Comment by HarryL5004** [comment]
@bashbashbash 
`450:	_, err = wallet.Write(updatedWalletJSON)`

I think there's still a problem with the tests for `getBalance` and `getStateNonce`. The `(File*).Write(...)` function currently only append the data into the existing file, it doesn't overwrite whatever is in the file. I suggest using the`ioutil.WriteFile(...)` function, which truncates a file before writing into the file.

**Comment by bashbashbash** [comment]
I prepared a branch called walletFunctions that has the revised versions of TestGetStateNonce and TestGetBalance (TestGetWalletAddress remains the same). This branch has the two tests in question create a wallet rather than access a wallet. Try this new branch with you functions and hopefully all goes well.

**Comment by HarryL5004** [comment]
@bashbashbash I was able to pass the tests in the walletFunctions branch. Should I push the changes to that branch?

**Comment by bashbashbash** [comment]
Yes - and great to hear!

**Comment by HarryL5004** [comment]
completed
